### PR TITLE
angler: update blobs from MMB29V images (this pull req includes an intermediate commit to MMB29Q)

### PR DESCRIPTION
**Pull request by nuclearmistake**
could be a no-op... but tested and working with latest vendor.img flashed, etc.

Change-Id: I8cde219870248c67fd1d0e47415912e7f08a4a06

### CODE REVIEW

**Comment by sam3000** [comment]
Could you please put up a gerrit for your corresponding extract-files / setup-makefiles changes ?

**Comment by sam3000** [comment]
(because your makefiles in this pull request show changes)

**Comment by nuclearmistake** [comment]
You asked for it! http://review.cyanogenmod.org/#/c/131312/

I know it's a hack... and definitely unconventional as far as CM extract-files processes... but seems to do the job?

**Comment by scotthartbti** [comment]
Any word on this?

**Comment by nuclearmistake** [comment]
Sam, any issues?

**Comment by zymphad** [comment]
What issues are there with this addition?

**Comment by nuclearmistake** [comment]
The blobs themselves work fine. I've been using them for a month. The issue is more the modified automagic extractor and associated proprietary-files.txt change http://review.cyanogenmod.org/#/c/131312/1

**Comment by nuclearmistake** [comment]
LGTM. Ship it IMO.

**Comment by scotthartbti** [comment]
I haven't had any issues on my end either and have been using them since
the first day.

**Comment by nuclearmistake** [comment]
Aye. Latest version is only -2 files, -2 lines, and with 2 binaries changed relative to the original pull request... And the latest version made my wayward "advanced LTE features" checkbox come back. Lol

**Comment by scotthartbti** [comment]
Ah.. So you made a few minor changes... Thanks... I'll repick.

**Comment by zymphad** [comment]
Been using them too, don't see why this hasn't been changed yet, it's been over a month.

**Comment by nuclearmistake** [comment]
g2g w/ MMB29V - just needs http://review.cyanogenmod.org/#/c/135452/ and might need associated android-6.0.1_r17 manifest changes and cm-tracked repo changes... with which I'm testing

**Comment by scotthartbti** [comment]
Awesome dude... Your always so quick to get the blobs and fingerprint
updated.  Much appreciated.

**Comment by nuclearmistake** [comment]
@Sam3000 this now brings the blobs up to date w/ MHC19I , with the prop overrides from http://review.cyanogenmod.org/#/c/135833

**Pull request merged**
