### PR TITLE
Add hi6250-common

### PR DESCRIPTION
**Pull request by DarkJoker360**

### CODE REVIEW

**Comment by DarkJoker360** [comment]
Assigned to: @npjohnson

**Comment by haggertk** [comment]
How does this possibly have a 2018 starting copyright year. Fix your scripts.

**Comment by DarkJoker360** [comment]
Because on our script the initial copyright year was set already to 2018. Shall I change it with 2020?

**Comment by npjohnson** [comment]
Yes

**Comment by DarkJoker360** [comment]
Hello, now it should be fine.
Added also these changes:
https://review.lineageos.org/c/LineageOS/android_device_huawei_anne/+/285275
https://review.lineageos.org/c/LineageOS/android_device_huawei_figo/+/285274

**Pull request merged**
